name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: smarterdm/docker-node-gettext-awscli:latest; smarterdm/docker-node-gettext-awscli:${{ github.run_number }}
